### ISSUE TITLE
buckboost converter simulation issue

### ISSUE THREAD

**Issue by vasu9009** [kanedahiroshi/LTspiceControlLibrary#1]
Hi Sir,

I have added LTspiceControlLibrary in my LTSPICE sub and sym folders.I am trying to simulate bidirectional buck boost converter but unable simulate it due to below error.Please resolve issue.

Error : could not open library file LTspicecontrollibrary\math.lib

Thanks
Srinivas
<img width="960" alt="math lib problem" src="https://user-images.githubusercontent.com/41154661/42633173-3e7a1d44-85fd-11e8-80b9-bedbc3acdfa2.PNG">

**Comment by kanedahiroshi** [comment]
It seems that the installation of the library files (*.lib) has not been done properly.
Did you unzip the downloaded file and run the install script "LTspiceControlLibrary\installXVII.bat"?
If the installation is done properly, you can find the library files (*.lib) in "%USERPROFILE%\Documents\LTspiceXVII\lib\sub\LTspiceControlLibrary".

**Comment by vasu9009** [comment]
Dear Sir,

Thank you for solution.After run the install script "LTspiceControlLibrary\installXVII.bat" examples are working.

Thanks
Srinivas
